### ISSUE TITLE
pretrained model folder location

### ISSUE THREAD

**Issue by surfingnirvana** [Mehrab-Kalantari/Structure-Aware-Style-Transfer#1]
Where do i have to place the pretrained model files? Also i get this error: FileNotFoundError: [Errno 2] No such file or directory: .../Artistic-Texture-Control/tools/global_edits/trained_models/AST/last.ckpt'

**Comment by Mehrab-Kalantari** [comment]
Unfortunately there is no pretrained model for this project.
It's just a simple implementation and presentation for university purposes
